### ISSUE TITLE
Auto update support 

### ISSUE THREAD

**Issue by CHEF-KOCH** [DominicTobias/SecurePad#5]
Instead of pushing the binary folder in the repo I suggests to pull it on GitHub's 'releases' page in a structure like:

- SecurePad_v<number>_UNI.zip
- SecurePad_v<number>_x64.zip

So that we can work with the [Plugin Manager](https://github.com/bruderstein/nppPluginManager/releases) to install/update the addon automatically.

**Comment by DominicTobias** [comment]
Sorry it took so long I forgot about the PR, merged now

**Comment by chcg** [comment]
@DominicTobias Would you like to register this repo at appveyor CI build service at https://ci.appveyor.com/signup. You can login with the github account. The config is already there you just need to add the project then without a configuration via the web interface. Additionally you could add a security token, see https://www.appveyor.com/docs/deployment/github/#provider-settings and build and publish github releases on creating tags that way. Otherwise I could just create a tag with the version build via my appveyor instance.

**Comment by chcg** [comment]
Created https://github.com/DominicTobias/SecurePad/releases/tag/v2.2.
Added to https://github.com/bruderstein/npp-plugins-x64/commit/b55173c730695fcc9c60945591a4ef93f0012124 and https://npppm.bruderste.in/plugins/view/securepad

https://github.com/notepad-plus-plus/nppPluginList will follow soon.
